export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const IS_LOG_IN = 'IS_LOG_IN'

export const FETCH_ROOM_REQUEST = 'FETCH_ROOM_REQUEST';
export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS';
export const FETCH_ROOM_FAILURE = 'FETCH_ROOM_FAILURE';


export const FETCH_THEATER_REQUEST = 'FETCH_THEATER_REQUEST';
export const FETCH_THEATER_SUCCESS = 'FETCH_THEATER_SUCCESS';
export const FETCH_THEATER_FAILURE = 'FETCH_THEATER_FAILURE';


export const CREATE_BILL_REQUEST = 'CREATE_BILL_REQUEST';
export const CREATE_BILL_SUCCESS = 'CREATE_BILL_SUCCESS';
export const CREATE_BILL_FAILURE = 'CREATE_BILL_FAILURE';


export const GET_FOODS_REQUEST = 'GET_FOODS_REQUEST';
export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS';
export const GET_FOODS_FAILURE = 'GET_FOODS_FAILURE';

export const GET_FOOD_BY_ID_REQUEST = 'GET_FOOD_BY_ID_REQUEST';
export const GET_FOOD_BY_ID_SUCCESS = 'GET_FOOD_BY_ID_SUCCESS';
export const GET_FOOD_BY_ID_FAILURE = 'GET_FOOD_BY_ID_FAILURE';


